title: 'Canadian Wanderlust'
default_lang: en
author:
  name: 'Tim Baker'
  email: timbaker@canadianwanderlust.com
  copyright: 'Copyright 2013 Deliver. All Rights Reserved.'
taxonomies:
  - category
  - tag
metadata:
  description: 'Canadian Wanderlust is our travel blog site for our travels through southeast asia'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
routes:
  /something/else: /blog/sample-3
  /another/one/here: /blog/sample-3
  '/new/*': '/blog/*'
blog:
  route: /blog
social:
  -
    url: 'https://twitter.com/getgrav'
    icon: twitter
  -
    url: '#'
    icon: facebook
  -
    url: blog.rss
    icon: rss
contact:
  address:
    -
      line: '222 Ave C South'
    -
      line: 'Saskatoon, Saskatchewan'
    -
      line: 'Canada S7K 2N5'
  gps: 1.306.222.3456
othermenu:
  -
    text: About
    url: about
  -
    text: 'Privacy Policy'
    url: '#'
  -
    text: Contact
    url: contact
quicklinks:
  -
    text: Portfolio
    url: 'base_url:portfolio'
  -
    text: About
    url: 'base_url:about'
  -
    text: Services
    url: 'base_url:services'
  -
    text: Archive
    url: 'base_url:archive'
  -
    text: Blog
    url: 'base_url:blog'
  -
    text: 'Contact Us'
    url: 'base_url:contact'
header_options:
  arrows: 'true'
  autoslide: 'false'
  autoslideHoverStop: 'false'
  interval: '2000'
  loop: 'false'
  transition: zoom
  itemsForSlide: '0'
  touch: 'true'
  swipe: 'true'
footer:
  description: 'Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras mattis consectetur purus sit amet fermentum. Curabitur blandit tempus porttitor. Cras justo odio, dapibus ac facilisis in, egestas eget quam.'
  contact_title: 'Contact Info'
  links_title: 'Quick Links'
  newsletter_title: Newsletter
  newsletter_description: 'Etiam porta sem malesuada magna mollis euismod.'
  copyright_text: 'Copyright 2013 Deliver. All Rights Reserved.'
  feedburner: ''
